; HW sound channel register base addresses
HW_CH1_BASE EQU (rNR10 % $100)
HW_CH2_BASE EQU ((rNR21 % $100) - 1)
HW_CH3_BASE EQU (rNR30 % $100)
HW_CH4_BASE EQU ((rNR41 % $100) - 1)

; HW sound channel enable bit masks
HW_CH1_ENABLE_MASK EQU %00010001
HW_CH2_ENABLE_MASK EQU %00100010
HW_CH3_ENABLE_MASK EQU %01000100
HW_CH4_ENABLE_MASK EQU %10001000

; HW sound channel disable bit masks
HW_CH1_DISABLE_MASK EQU (~HW_CH1_ENABLE_MASK & $ff)
HW_CH2_DISABLE_MASK EQU (~HW_CH2_ENABLE_MASK & $ff)
HW_CH3_DISABLE_MASK EQU (~HW_CH3_ENABLE_MASK & $ff)
HW_CH4_DISABLE_MASK EQU (~HW_CH4_ENABLE_MASK & $ff)

REG_DUTY_SOUND_LEN  EQU 1
REG_VOLUME_ENVELOPE EQU 2
REG_FREQUENCY_LO    EQU 3

MAX_SFX_ID EQU $B9

CRY_SFX_START EQU $14
CRY_SFX_END   EQU $86

; wChannelFlags1 constants
BIT_PERFECT_PITCH         EQU 0 ; controlled by toggleperfectpitch command
BIT_CHANNEL_CALL          EQU 1 ; if in channel call
BIT_NOISE_OR_SFX          EQU 2 ; if channel is the music noise channel or an SFX channel
BIT_VIBRATO_DIRECTION     EQU 3 ; if the pitch is above or below normal (cycles)
BIT_PITCH_BEND_ON         EQU 4 ; if pitch bend is active
BIT_PITCH_BEND_DECREASING EQU 5 ; if the pitch bend frequency is decreasing (instead of increasing)
BIT_ROTATE_DUTY           EQU 6 ; if rotating duty

; wChannelFlags2 constant (only has one flag)
BIT_EXECUTE_MUSIC EQU 0 ; if in execute music

; Song ids are calculated by address to save space.

;music_const: MACRO
;\1 EQUS "RB(\2)"
;ENDM
const_value = 1

	const MUSIC_PALLET_TOWN
	const MUSIC_POKECENTER
	const MUSIC_GYM
	const MUSIC_CITIES1
	const MUSIC_CITIES2
	const MUSIC_CELADON
	const MUSIC_CINNABAR
	const MUSIC_VERMILION
	const MUSIC_LAVENDER
	const MUSIC_SS_ANNE
	const MUSIC_MEET_PROF_OAK
	const MUSIC_MEET_RIVAL
	const MUSIC_MUSEUM_GUY
	const MUSIC_SAFARI_ZONE
	const MUSIC_PKMN_HEALED
	const MUSIC_ROUTES1
	const MUSIC_ROUTES2
	const MUSIC_ROUTES3
	const MUSIC_ROUTES4
	const MUSIC_INDIGO_PLATEAU
	
	const MUSIC_GYM_LEADER_BATTLE
	const MUSIC_TRAINER_BATTLE
	const MUSIC_WILD_BATTLE
	const MUSIC_FINAL_BATTLE
	const MUSIC_DEFEATED_TRAINER
	const MUSIC_DEFEATED_WILD_MON
	const MUSIC_DEFEATED_GYM_LEADER
	
	const MUSIC_TITLE_SCREEN
	const MUSIC_CREDITS
	const MUSIC_HALL_OF_FAME
	const MUSIC_OAKS_LAB
	const MUSIC_JIGGLYPUFF_SONG
	const MUSIC_BIKE_RIDING
	const MUSIC_SURFING
	const MUSIC_GAME_CORNER
	const MUSIC_INTRO_BATTLE
	const MUSIC_DUNGEON1
	const MUSIC_DUNGEON2
	const MUSIC_DUNGEON3
	const MUSIC_CINNABAR_MANSION
	const MUSIC_POKEMON_TOWER
	const MUSIC_SILPH_CO
	const MUSIC_MEET_EVIL_TRAINER
	const MUSIC_MEET_FEMALE_TRAINER
	const MUSIC_MEET_MALE_TRAINER
	
	const MUSIC_MT_MOON_SQUARE
	const MUSIC_ABANDONED_SHIP
	const MUSIC_LAKE_OF_RAGE

	; GBP-5.56.01: GB Player-only IDs extend the existing Music pointer table.
	; Existing map/battle IDs 1..48 remain unchanged.
	const MUSIC_GBP_GSC_ROUTE36
	const MUSIC_GBP_GSC_RIVAL_BATTLE
	const MUSIC_GBP_GSC_ROCKET_BATTLE
	const MUSIC_GBP_GSC_ELMS_LAB
	const MUSIC_GBP_GSC_DARK_CAVE
	const MUSIC_GBP_GSC_JOHTO_GYM_BATTLE
	const MUSIC_GBP_GSC_CHAMPION_BATTLE
	const MUSIC_GBP_GSC_SS_AQUA
	const MUSIC_GBP_GSC_NEW_BARK_TOWN
	const MUSIC_GBP_GSC_GOLDENROD_CITY
	const MUSIC_GBP_GSC_VERMILION_CITY
	const MUSIC_GBP_GSC_TITLE_SCREEN
	const MUSIC_GBP_GSC_RUINS_OF_ALPH_INTERIOR
	const MUSIC_GBP_GSC_LOOK_POKEMANIAC
	const MUSIC_GBP_GSC_TRAINER_VICTORY
	const MUSIC_GBP_GSC_ROUTE1
	const MUSIC_GBP_GSC_ROUTE3
	const MUSIC_GBP_GSC_ROUTE12
	const MUSIC_GBP_GSC_KANTO_GYM_BATTLE
	const MUSIC_GBP_GSC_KANTO_WILD_BATTLE
	const MUSIC_GBP_GSC_POKEMON_CENTER
	const MUSIC_GBP_GSC_LOOK_LASS
	const MUSIC_GBP_GSC_LOOK_OFFICER
	const MUSIC_GBP_GSC_ROUTE2
	const MUSIC_GBP_GSC_MT_MOON
	const MUSIC_GBP_GSC_SHOW_ME_AROUND
	const MUSIC_GBP_GSC_GAME_CORNER
	const MUSIC_GBP_GSC_BICYCLE
	const MUSIC_GBP_GSC_LOOK_SAGE
	const MUSIC_GBP_GSC_POKEMON_CHANNEL
	const MUSIC_GBP_GSC_LIGHTHOUSE
	const MUSIC_GBP_GSC_LAKE_OF_RAGE
	const MUSIC_GBP_GSC_INDIGO_PLATEAU
	const MUSIC_GBP_GSC_ROUTE37
	const MUSIC_GBP_GSC_ROCKET_HIDEOUT
	const MUSIC_GBP_GSC_DRAGONS_DEN
	const MUSIC_GBP_GSC_RUINS_OF_ALPH_RADIO
	const MUSIC_GBP_GSC_LOOK_BEAUTY
	const MUSIC_GBP_GSC_ROUTE26
	const MUSIC_GBP_GSC_ECRUTEAK_CITY
	const MUSIC_GBP_GSC_LAKE_OF_RAGE_ROCKET_RADIO
	const MUSIC_GBP_GSC_MAGNET_TRAIN
	const MUSIC_GBP_GSC_LAVENDER_TOWN
	const MUSIC_GBP_GSC_DANCING_HALL
	const MUSIC_GBP_GSC_CONTEST_RESULTS
	const MUSIC_GBP_GSC_ROUTE30
	const MUSIC_GBP_GSC_VIOLET_CITY
	const MUSIC_GBP_GSC_ROUTE29
	const MUSIC_GBP_GSC_HALL_OF_FAME
	const MUSIC_GBP_GSC_HEAL_POKEMON
	const MUSIC_GBP_GSC_EVOLUTION
	const MUSIC_GBP_GSC_PRINTER
	const MUSIC_GBP_GSC_VIRIDIAN_CITY
	const MUSIC_GBP_GSC_CELADON_CITY
	const MUSIC_GBP_GSC_WILD_POKEMON_VICTORY
	const MUSIC_GBP_GSC_SUCCESSFUL_CAPTURE
	const MUSIC_GBP_GSC_GYM_LEADER_VICTORY
	const MUSIC_GBP_GSC_MT_MOON_SQUARE
	const MUSIC_GBP_GSC_GYM
	const MUSIC_GBP_GSC_PALLET_TOWN
	const MUSIC_GBP_GSC_PROF_OAKS_POKEMON_TALK
	const MUSIC_GBP_GSC_PROF_OAK
	const MUSIC_GBP_GSC_LOOK_RIVAL
	const MUSIC_GBP_GSC_AFTER_THE_RIVAL_FIGHT
	const MUSIC_GBP_GSC_SURF
	const MUSIC_GBP_GSC_NATIONAL_PARK
	const MUSIC_GBP_GSC_AZALEA_TOWN
	const MUSIC_GBP_GSC_CHERRYGROVE_CITY
	const MUSIC_GBP_GSC_UNION_CAVE
	const MUSIC_GBP_GSC_JOHTO_WILD_BATTLE
	const MUSIC_GBP_GSC_JOHTO_WILD_BATTLE_NIGHT
	const MUSIC_GBP_GSC_JOHTO_TRAINER_BATTLE
	const MUSIC_GBP_GSC_LOOK_YOUNGSTER
	const MUSIC_GBP_GSC_TIN_TOWER
	const MUSIC_GBP_GSC_SPROUT_TOWER
	const MUSIC_GBP_GSC_BURNED_TOWER
	const MUSIC_GBP_GSC_MOM
	const MUSIC_GBP_GSC_VICTORY_ROAD
	const MUSIC_GBP_GSC_POKEMON_LULLABY
	const MUSIC_GBP_GSC_POKEMON_MARCH
	const MUSIC_GBP_GSC_GOLD_SILVER_OPENING
	const MUSIC_GBP_GSC_GOLD_SILVER_OPENING2
	const MUSIC_GBP_GSC_LOOK_HIKER
	const MUSIC_GBP_GSC_LOOK_ROCKET
	const MUSIC_GBP_GSC_ROCKET_THEME
	const MUSIC_GBP_GSC_MAIN_MENU
	const MUSIC_GBP_GSC_LOOK_KIMONO_GIRL
	const MUSIC_GBP_GSC_POKE_FLUTE_CHANNEL
	const MUSIC_GBP_GSC_BUG_CATCHING_CONTEST
	const MUSIC_GBP_GSC_KANTO_TRAINER_BATTLE
	const MUSIC_GBP_GSC_CREDITS
	const MUSIC_GBP_GSC_POST_CREDITS
	const MUSIC_GBP_GSC_CLAIR
	const MUSIC_GBP_GSC_MOBILE_ADAPTER_MENU
	const MUSIC_GBP_GSC_MOBILE_ADAPTER
	const MUSIC_GBP_GSC_BUENAS_PASSWORD
	const MUSIC_GBP_GSC_LOOK_MYSTICAL_MAN
	const MUSIC_GBP_GSC_CRYSTAL_OPENING
	const MUSIC_GBP_GSC_BATTLE_TOWER_THEME
	const MUSIC_GBP_GSC_SUICUNE_BATTLE
	const MUSIC_GBP_GSC_BATTLE_TOWER_LOBBY
	const MUSIC_GBP_GSC_MOBILE_CENTER
	const MUSIC_GBP_CUSTOM_JOHTO_GSC
	const MUSIC_GBP_CUSTOM_CERULEAN_GSC
	const MUSIC_GBP_CUSTOM_CINNABAR_GSC
	const MUSIC_GBP_CUSTOM_NUGGET_BRIDGE
	const MUSIC_GBP_CUSTOM_SHOP
	const MUSIC_GBP_CUSTOM_POKEATHELON_FINAL
	const MUSIC_GBP_CUSTOM_NALJO_WILD_BATTLE
	const MUSIC_GBP_CUSTOM_NALJO_GYM_BATTLE
	const MUSIC_GBP_CUSTOM_PALLET_BATTLE
	const MUSIC_GBP_CUSTOM_CINNABAR_REMIX
	const MUSIC_GBP_CUSTOM_KANTO_GYM_LEADER_REMIX

const_value = 1
	; AUDIO_1 AUDIO_3
	const SFX_GET_ITEM_1

	; AUDIO_1 AUDIO_2 AUDIO_3
	const SFX_GET_ITEM_2
	const SFX_TINK
	const SFX_HEAL_HP
	const SFX_HEAL_AILMENT
	const SFX_START_MENU
	const SFX_PRESS_AB

	; AUDIO_1 AUDIO_3
	const SFX_POKEDEX_RATING
	const SFX_GET_KEY_ITEM
	const SFX_POISONED
	const SFX_TRADE_MACHINE
	const SFX_TURN_ON_PC
	const SFX_TURN_OFF_PC
	const SFX_ENTER_PC
	const SFX_SHRINK
	const SFX_SWITCH
	const SFX_HEALING_MACHINE
	const SFX_TELEPORT_EXIT_1
	const SFX_TELEPORT_ENTER_1
	const SFX_TELEPORT_EXIT_2
	const SFX_LEDGE
	const SFX_TELEPORT_ENTER_2
	const SFX_FLY
	const SFX_DENIED
	const SFX_ARROW_TILES
	const SFX_PUSH_BOULDER
	const SFX_SS_ANNE_HORN
	const SFX_WITHDRAW_DEPOSIT
	const SFX_CUT
	const SFX_GO_INSIDE
	const SFX_SWAP
	const SFX_59
	const SFX_PURCHASE
	const SFX_COLLISION
	const SFX_GO_OUTSIDE
	const SFX_SAVE

	; AUDIO_1
	const SFX_POKEFLUTE
	const SFX_SAFARI_ZONE_PA

	; AUDIO_2
	const SFX_LEVEL_UP

	const SFX_BALL_TOSS
	const SFX_BALL_POOF
	const SFX_FAINT_THUD
	const SFX_RUN
	const SFX_DEX_PAGE_ADDED
	const SFX_CAUGHT_MON
	const SFX_PECK
	const SFX_FAINT_FALL
	const SFX_BATTLE_09
	const SFX_POUND
	const SFX_BATTLE_0B
	const SFX_BATTLE_0C
	const SFX_BATTLE_0D
	const SFX_BATTLE_0E
	const SFX_BATTLE_0F
	const SFX_DAMAGE
	const SFX_NOT_VERY_EFFECTIVE
	const SFX_BATTLE_12
	const SFX_BATTLE_13
	const SFX_BATTLE_14
	const SFX_VINE_WHIP
	const SFX_BATTLE_16
	const SFX_BATTLE_17
	const SFX_BATTLE_18
	const SFX_BATTLE_19
	const SFX_SUPER_EFFECTIVE
	const SFX_BATTLE_1B
	const SFX_BATTLE_1C
	const SFX_DOUBLESLAP
	const SFX_BATTLE_1E
	const SFX_HORN_DRILL
	const SFX_BATTLE_20
	const SFX_BATTLE_21
	const SFX_BATTLE_22
	const SFX_BATTLE_23
	const SFX_BATTLE_24
	const SFX_BATTLE_25
	const SFX_BATTLE_26
	const SFX_BATTLE_27
	const SFX_BATTLE_28
	const SFX_BATTLE_29
	const SFX_BATTLE_2A
	const SFX_BATTLE_2B
	const SFX_BATTLE_2C
	const SFX_PSYBEAM
	const SFX_BATTLE_2E
	const SFX_BATTLE_2F
	const SFX_PSYCHIC_M
	const SFX_BATTLE_31
	const SFX_BATTLE_32
	const SFX_BATTLE_33
	const SFX_BATTLE_34
	const SFX_BATTLE_35
	const SFX_BATTLE_36
	const SFX_SILPH_SCOPE

	; AUDIO_3
	const SFX_INTRO_LUNGE
	const SFX_INTRO_HIP
	const SFX_INTRO_HOP
	const SFX_INTRO_RAISE
	const SFX_INTRO_CRASH
	const SFX_INTRO_WHOOSH
	const SFX_SLOTS_STOP_WHEEL
	const SFX_SLOTS_REWARD
	const SFX_SLOTS_NEW_SPIN
	const SFX_SHOOTING_STAR

	const GSSFX_NOT_VERY_EFFECTIVE
	const GSSFX_DAMAGE
	const GSSFX_SUPER_EFFECTIVE
