; GBP-5.56.01: GB Player-only continuation of the normal Music pointer table.
; IDs are defined after the existing 48 runtime music IDs, so normal gameplay
; keeps every legacy ID stable while the player can address the retained library.

; GSC: 92 Gold/Silver songs followed by 10 Crystal-exclusive songs.
	tbp Music_Route36
	tbp Music_RivalBattle
	tbp Music_RocketBattle
	tbp Music_ElmsLab
	tbp Music_DarkCave
	tbp Music_JohtoGymBattle
	tbp Music_ChampionBattle
	tbp Music_SSAqua
	tbp Music_NewBarkTown
	tbp Music_GoldenrodCity
	tbp Music_VermilionCity
	tbp Music_TitleScreen
	tbp Music_RuinsOfAlphInterior
	tbp Music_LookPokemaniac
	tbp Music_TrainerVictory
	tbp Music_Route1
	tbp Music_Route3
	tbp Music_Route12
	tbp Music_KantoGymBattle
	tbp Music_KantoWildBattle
	tbp Music_PokemonCenter
	tbp Music_LookLass
	tbp Music_LookOfficer
	tbp Music_Route2
	tbp Music_MtMoon
	tbp Music_ShowMeAround
	tbp Music_GameCorner
	tbp Music_Bicycle
	tbp Music_LookSage
	tbp Music_PokemonChannel
	tbp Music_Lighthouse
	tbp Music_LakeOfRage
	tbp Music_IndigoPlateau
	tbp Music_Route37
	tbp Music_RocketHideout
	tbp Music_DragonsDen
	tbp Music_RuinsOfAlphRadio
	tbp Music_LookBeauty
	tbp Music_Route26
	tbp Music_EcruteakCity
	tbp Music_LakeOfRageRocketRadio
	tbp Music_MagnetTrain
	tbp Music_LavenderTown
	tbp Music_DancingHall
	tbp Music_ContestResults
	tbp Music_Route30
	tbp Music_VioletCity
	tbp Music_Route29
	tbp Music_HallOfFame
	tbp Music_HealPokemon
	tbp Music_Evolution
	tbp Music_Printer
	tbp Music_ViridianCity
	tbp Music_CeladonCity
	tbp Music_WildPokemonVictory
	tbp Music_SuccessfulCapture
	tbp Music_GymLeaderVictory
	tbp Music_MtMoonSquare
	tbp Music_Gym
	tbp Music_PalletTown
	tbp Music_ProfOaksPokemonTalk
	tbp Music_ProfOak
	tbp Music_LookRival
	tbp Music_AfterTheRivalFight
	tbp Music_Surf
	tbp Music_NationalPark
	tbp Music_AzaleaTown
	tbp Music_CherrygroveCity
	tbp Music_UnionCave
	tbp Music_JohtoWildBattle
	tbp Music_JohtoWildBattleNight
	tbp Music_JohtoTrainerBattle
	tbp Music_LookYoungster
	tbp Music_TinTower
	tbp Music_SproutTower
	tbp Music_BurnedTower
	tbp Music_Mom
	tbp Music_VictoryRoad
	tbp Music_PokemonLullaby
	tbp Music_PokemonMarch
	tbp Music_GoldSilverOpening
	tbp Music_GoldSilverOpening2
	tbp Music_LookHiker
	tbp Music_LookRocket
	tbp Music_RocketTheme
	tbp Music_MainMenu
	tbp Music_LookKimonoGirl
	tbp Music_PokeFluteChannel
	tbp Music_BugCatchingContest
	tbp Music_KantoTrainerBattle
	tbp Music_Credits
	tbp Music_PostCredits
	tbp Music_Clair
	tbp Music_MobileAdapterMenu
	tbp Music_MobileAdapter
	tbp Music_BuenasPassword
	tbp Music_LookMysticalMan
	tbp Music_CrystalOpening
	tbp Music_BattleTowerTheme
	tbp Music_SuicuneBattle
	tbp Music_BattleTowerLobby
	tbp Music_MobileCenter

; Custom: every non-empty custom track restored in MUS-5.54.03.
	tbp Music_JohtoGSC
	tbp Music_CeruleanGSC
	tbp Music_CinnabarGSC
	tbp Music_NuggetBridge
	tbp Music_Shop
	tbp Music_PokeathelonFinal
	tbp Music_NaljoWildBattle
	tbp Music_NaljoGymBattle
	tbp Music_PalletBattle
	tbp Music_CinnabarRemix
	tbp Music_KantoGymLeaderRemix
