; Compact Bag/Mart item descriptions.
; The old Bag-only INFO page and its duplicate long-description pointer table
; were removed. Normal items use the shared two-line Mart descriptions below;
; TM/HM descriptions are generated from the live move data instead.

; INPUT: D = HM_01..HM_05 or TM_01..TM_50.
; D is used deliberately because callab/Bankswitch does not preserve A/BC/HL.
; Draws the compact machine summary used by Bag/Mart:
;   TM01  DynamicPunch
; The machine label is generated by GetMachineName and the move name is read
; from the live TechnicalMachines/MoveNames data, so neither is hard-coded here.
DrawMachineItemDescription::
	; Draw the real machine label first (TM01/HM01). The description area has
	; already been cleared, so starting the move name at x=7 leaves exactly
	; two spaces between the four-character machine label and the move name.
	; GetItemName is the safe public helper here: unlike GetMachineName, it
	; returns DE = wcd6d for PlaceString. Preserve the selected item ID because
	; that returned DE necessarily overwrites D.
	push de
	ld a, d
	ld [wd11e], a
	call GetItemName
	coord hl, 1, 14
	call PlaceString
	pop de

	; Convert the selected machine item to its current move dynamically.
	ld a, d
	cp TM_01
	jr nc, .tm
	sub HM_01
	add 51 ; HMs are entries 51..55 in TechnicalMachines
	jr .haveMachineNumber
.tm
	sub TM_01 - 1 ; TM01..TM50 -> 1..50
.haveMachineNumber
	ld [wd11e], a
	callba TMToMove
	call GetMoveName
	coord hl, 7, 14
	call PlaceString
	ret

EmptyDescription:
	TX_FAR _EmptyDescription
	db "@"

; Bag pocket descriptions calculate a pointer into ItemDescriptionPointers_Mart
; from bank $35. Bankswitch here, restore that pointer from de, then reuse the
; Home text renderer without recreating the MESSAGE_BOX or adding another Delay3.
PrintBagItemDescriptionText::
	ld h, d
	ld l, e
	jp PrintText_NoCreatingTextBox

FlashItemDescription_Mart:
	; d = item id
	ld a, d
	cp $ff
	jr z, .empty
	cp HM_01
	jr c, .normal
	cp TM_50 + 1
	jr c, .machine
.normal
	dec a
	ld hl, ItemDescriptionPointers_Mart
	ld bc, 5
.add
	and a
	jr z, .normalReady
	dec a
	add hl, bc
	jr .add
.empty
	ld hl, EmptyDescription
.normalReady
	push hl
	ld hl, wd730
	set 6, [hl]
	pop hl
	; Draw the whole description into the background tilemap before
	; transferring it, so clearing the old text is never shown onscreen.
	ld a, [H_AUTOBGTRANSFERENABLED]
	push af
	xor a
	ld [H_AUTOBGTRANSFERENABLED], a
	call PrintText
	jr .finishDraw

.machine
	ld hl, wd730
	set 6, [hl]
	ld a, [H_AUTOBGTRANSFERENABLED]
	push af
	xor a
	ld [H_AUTOBGTRANSFERENABLED], a
	; Recreate/clear the normal MESSAGE_BOX just like PrintText does for
	; ordinary Mart descriptions, then draw the dynamic machine data into it.
	push de
	ld hl, EmptyDescription
	call PrintText
	pop de
	call DrawMachineItemDescription

.finishDraw
	pop af
	ld [H_AUTOBGTRANSFERENABLED], a
	; Do not add another wait here. Mart menu paths reach their normal Delay3
	; before polling again, so list, cursor, and description transfer together.
	ld hl, wd730
	res 6, [hl]
	ret

ItemDescriptionPointers_Mart:
	TX_FAR _MasterBallDescription_Mart
	db "@"
	TX_FAR _UltraBallDescription_Mart
	db "@"
	TX_FAR _GreatBallDescription_Mart
	db "@"
	TX_FAR _PokeBallDescription_Mart
	db "@"
	TX_FAR _TownMapDescription_Mart
	db "@"
	TX_FAR _BicycleDescription_Mart
	db "@"
	TX_FAR _SurfboardDescription_Mart
	db "@"
	TX_FAR _SafariBallDescription_Mart
	db "@"
	TX_FAR _PokedexDescription_Mart
	db "@"
	TX_FAR _MoonStoneDescription_Mart
	db "@"
	TX_FAR _AntidoteDescription_Mart
	db "@"
	TX_FAR _BurnHealDescription_Mart
	db "@"
	TX_FAR _IceHealDescription_Mart
	db "@"
	TX_FAR _AwakeningDescription_Mart
	db "@"
	TX_FAR _ParalyzeHealDescription_Mart
	db "@"
	TX_FAR _FullRestoreDescription_Mart
	db "@"
	TX_FAR _MaxPotionDescription_Mart
	db "@"
	TX_FAR _HyperPotionDescription_Mart
	db "@"
	TX_FAR _SuperPotionDescription_Mart
	db "@"
	TX_FAR _PotionDescription_Mart
	db "@"
	TX_FAR _SafariBaitDescription_Mart
	db "@"
	TX_FAR _SafariRockDescription_Mart
	db "@"
	TX_FAR _OldSeaMapDescription_Mart
	db "@"
	TX_FAR _MysticTicketDescription_Mart
	db "@"
	TX_FAR _EonTicketDescription_Mart
	db "@"
	TX_FAR _TeruSama1ADescription_Mart
	db "@"
	TX_FAR _TeruSama1BDescription_Mart
	db "@"
	TX_FAR _TeruSama1CDescription_Mart
	db "@"
	TX_FAR _EscapeRopeDescription_Mart
	db "@"
	TX_FAR _RepelDescription_Mart
	db "@"
	TX_FAR _OldAmberDescription_Mart
	db "@"
	TX_FAR _FireStoneDescription_Mart
	db "@"
	TX_FAR _ThunderStoneDescription_Mart
	db "@"
	TX_FAR _WaterStoneDescription_Mart
	db "@"
	TX_FAR _HPUpDescription_Mart
	db "@"
	TX_FAR _ProteinDescription_Mart
	db "@"
	TX_FAR _IronDescription_Mart
	db "@"
	TX_FAR _CarbosDescription_Mart
	db "@"
	TX_FAR _CalciumDescription_Mart
	db "@"
	TX_FAR _RareCandyDescription_Mart
	db "@"
	TX_FAR _DomeFossilDescription_Mart
	db "@"
	TX_FAR _HelixFossilDescription_Mart
	db "@"
	TX_FAR _SecretKeyDescription_Mart
	db "@"
	TX_FAR _SunStoneDescription_Mart
	db "@"
	TX_FAR _BikeVoucherDescription_Mart
	db "@"
	TX_FAR _XAccuracyDescription_Mart
	db "@"
	TX_FAR _LeafStoneDescription_Mart
	db "@"
	TX_FAR _CardKeyDescription_Mart
	db "@"
	TX_FAR _NuggetDescription_Mart
	db "@"
	TX_FAR _ThiefBallDescription_Mart
	db "@"
	TX_FAR _PokeDollDescription_Mart
	db "@"
	TX_FAR _FullHealDescription_Mart
	db "@"
	TX_FAR _ReviveDescription_Mart
	db "@"
	TX_FAR _MaxReviveDescription_Mart
	db "@"
	TX_FAR _GuardSpecDescription_Mart
	db "@"
	TX_FAR _SuperRepelDescription_Mart
	db "@"
	TX_FAR _MaxRepelDescription_Mart
	db "@"
	TX_FAR _DireHitDescription_Mart
	db "@"
	TX_FAR _CoinDescription_Mart
	db "@"
	TX_FAR _FreshWaterDescription_Mart
	db "@"
	TX_FAR _SodaPopDescription_Mart
	db "@"
	TX_FAR _LemonadeDescription_Mart
	db "@"
	TX_FAR _SSTicketDescription_Mart
	db "@"
	TX_FAR _GoldTeethDescription_Mart
	db "@"
	TX_FAR _XAttackDescription_Mart
	db "@"
	TX_FAR _XDefendDescription_Mart
	db "@"
	TX_FAR _XSpeedDescription_Mart
	db "@"
	TX_FAR _XSpecialDescription_Mart
	db "@"
	TX_FAR _CoinCaseDescription_Mart
	db "@"
	TX_FAR _OaksParcelDescription_Mart
	db "@"
	TX_FAR _ItemFinderDescription_Mart
	db "@"
	TX_FAR _SilphScopeDescription_Mart
	db "@"
	TX_FAR _PokeFluteDescription_Mart
	db "@"
	TX_FAR _LiftKeyDescription_Mart
	db "@"
	TX_FAR _EXPShareDescription_Mart
	db "@"
	TX_FAR _OldRodDescription_Mart
	db "@"
	TX_FAR _GoodRodDescription_Mart
	db "@"
	TX_FAR _SuperRodDescription_Mart
	db "@"
	TX_FAR _PPUpDescription_Mart
	db "@"
	TX_FAR _EtherDescription_Mart
	db "@"
	TX_FAR _MaxEtherDescription_Mart
	db "@"
	TX_FAR _ElixerDescription_Mart
	db "@"
	TX_FAR _MaxElixerDescription_Mart
	db "@"
	TX_FAR _FloorB2FDescription_Mart
	db "@"
	TX_FAR _FloorB1FDescription_Mart
	db "@"
	TX_FAR _Floor1FDescription_Mart
	db "@"
	TX_FAR _Floor2FDescription_Mart
	db "@"
	TX_FAR _Floor3FDescription_Mart
	db "@"
	TX_FAR _Floor4FDescription_Mart
	db "@"
	TX_FAR _Floor5FDescription_Mart
	db "@"
	TX_FAR _Floor6FDescription_Mart
	db "@"
	TX_FAR _Floor7FDescription_Mart
	db "@"
	TX_FAR _Floor8FDescription_Mart
	db "@"
	TX_FAR _Floor9FDescription_Mart
	db "@"
	TX_FAR _Floor10FDescription_Mart
	db "@"
	TX_FAR _Floor11FDescription_Mart
	db "@"
	TX_FAR _FloorB4FDescription_Mart
	db "@"
	TX_FAR _OranBerryDescription_Mart
	db "@"
	TX_FAR _SitrusBerryDescription_Mart
	db "@"
	TX_FAR _LeppaBerryDescription_Mart
	db "@"
	TX_FAR _PechaBerryDescription_Mart
	db "@"
	TX_FAR _RawstBerryDescription_Mart
	db "@"
	TX_FAR _AspearBerryDescription_Mart
	db "@"
	TX_FAR _ChestoBerryDescription_Mart
	db "@"
	TX_FAR _CheriBerryDescription_Mart
	db "@"
	TX_FAR _LumBerryDescription_Mart
	db "@"
	TX_FAR _SwegBerryDescription_Mart
	db "@"
	TX_FAR _GoHomeDescription_Mart
	db "@"
